# Generated by Django 4.0.1 on 2022-09-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('prescription', models.TextField()),
                ('medicine_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
                ('x_rays_id', models.IntegerField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='account.doctorprofile')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='account.patientprofile')),
            ],
        ),
    ]
