# Generated by Django 4.1.1 on 2022-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                ("prescription", models.TextField()),
                ("medicine_id", models.IntegerField()),
                ("test_id", models.IntegerField()),
                ("x_rays_id", models.IntegerField()),
            ],
        ),
    ]
