# Generated by Django 4.1.1 on 2022-09-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
