# Generated by Django 4.1.1 on 2022-09-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_patientprofile_blood_type"),
        ("visits", "0002_alter_visits_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="doctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="account.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="visits",
            name="lab_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab",
                to="account.labsprofile",
            ),
        ),
        migrations.AddField(
            model_name="visits",
            name="patient_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="account.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="visits",
            name="pharmacist_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharmacist",
                to="account.pharmacistprofile",
            ),
        ),
        migrations.AddField(
            model_name="visits",
            name="x_rays_lab_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="x_rays_lab",
                to="account.x_rays_labprofile",
            ),
        ),
    ]
