# Generated by Django 4.1.1 on 2022-09-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicesmanager", "0002_alter_tests_options"),
        ("visits", "0003_visits_doctor_id_visits_lab_id_visits_patient_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="medicine_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="servicesmanager.medicine",
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="test_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="servicesmanager.tests"
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="x_rays_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="servicesmanager.x_rays"
            ),
        ),
    ]
