# Generated by Django 4.1.1 on 2022-09-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_alter_visits_medicine_id_alter_visits_test_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visits",
            old_name="medicine_id",
            new_name="medicine",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="test_id",
            new_name="test",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="x_rays_id",
            new_name="x_rays",
        ),
    ]
