# Generated by Django 4.1.1 on 2022-09-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicesmanager", "0003_alter_medicine_names"),
        ("visits", "0006_alter_visits_medicine_alter_visits_test_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="test",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="servicesmanager.tests",
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="x_rays",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="servicesmanager.x_rays",
            ),
        ),
    ]
