# Generated by Django 4.1.1 on 2022-09-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicesmanager", "0003_alter_medicine_names"),
        ("visits", "0007_alter_visits_test_alter_visits_x_rays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="servicesmanager.medicine",
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="servicesmanager.tests",
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="x_rays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="x_rayss",
                to="servicesmanager.x_rays",
            ),
        ),
    ]
