# Generated by Django 4.1.1 on 2022-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0008_alter_visits_medicine_alter_visits_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="visit_status",
            field=models.BooleanField(default=True),
        ),
    ]
