# Generated by Django 4.1.1 on 2022-09-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0009_visits_visit_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visits",
            old_name="doctor_id",
            new_name="doctor",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="lab_id",
            new_name="lab",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="patient_id",
            new_name="patient",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="pharmacist_id",
            new_name="pharmacist",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="x_rays_lab_id",
            new_name="x_rays_lab",
        ),
    ]
