# Generated by Django 4.1.1 on 2022-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0010_rename_doctor_id_visits_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visits",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visits",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
