# Generated by Django 4.1.1 on 2022-09-19 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0011_alter_visits_description_alter_visits_prescription_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visits",
            old_name="prescription",
            new_name="test_attachments",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="summary",
            new_name="test_description",
        ),
        migrations.RemoveField(
            model_name="visits",
            name="lab",
        ),
        migrations.RemoveField(
            model_name="visits",
            name="pharmacist",
        ),
        migrations.RemoveField(
            model_name="visits",
            name="test",
        ),
        migrations.RemoveField(
            model_name="visits",
            name="x_rays",
        ),
        migrations.RemoveField(
            model_name="visits",
            name="x_rays_lab",
        ),
        migrations.AddField(
            model_name="visits",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visits",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visits",
            name="x_rays_attachments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visits",
            name="x_rays_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visits",
            name="medicine",
            field=models.TextField(blank=True, null=True),
        ),
    ]
