# Generated by Django 4.1.1 on 2022-09-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0012_rename_prescription_visits_test_attachments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visits",
            name="title",
        ),
    ]
