# Generated by Django 4.0.1 on 2022-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=255)),
                ('doses', models.IntegerField(blank=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('result_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('result_date', models.DateField(auto_now=True)),
                ('folder_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='X_Rays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('result_date', models.DateField(auto_now=True)),
                ('folder_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
