# Generated by Django 4.1.1 on 2022-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesmanager", "0002_alter_tests_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="names",
            field=models.TextField(blank=True),
        ),
    ]
