# Generated by Django 4.1.1 on 2022-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesmanager", "0003_alter_medicine_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="doses",
        ),
        migrations.AddField(
            model_name="medicine",
            name="sold_status",
            field=models.BooleanField(default=False),
        ),
    ]
