# Generated by Django 4.1.1 on 2022-09-10 19:58

from django.db import migrations, models
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_labs_pharmacist_x_rays_lab_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="doctor_id",
        ),
        migrations.RemoveField(
            model_name="labsprofile",
            name="labs_id",
        ),
        migrations.RemoveField(
            model_name="pharmacistprofile",
            name="pharmacist_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.RemoveField(
            model_name="x_rays_labprofile",
            name="x_rays_lab_id",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, null=True
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="labsprofile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="labsprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, null=True
            ),
        ),
        migrations.AddField(
            model_name="labsprofile",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="labsprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="pharmacistprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="x_rays_labprofile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="x_rays_labprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, null=True
            ),
        ),
        migrations.AddField(
            model_name="x_rays_labprofile",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="x_rays_labprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
