# Generated by Django 4.1.1 on 2022-09-11 07:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_managers_remove_doctorprofile_doctor_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="patient_id",
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[(0, "Male"), (1, "Female")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.IntegerField(
                blank=True, choices=[(0, "Male"), (1, "Female")], null=True
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
