# Generated by Django 4.1.1 on 2022-09-11 11:24

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_patientprofile_blood_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="31.959153316146658,35.91156005859375", max_length=63
            ),
        ),
        migrations.AlterField(
            model_name="labsprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="labsprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="31.959153316146658,35.91156005859375", max_length=63
            ),
        ),
        migrations.AlterField(
            model_name="pharmacistprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pharmacistprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="31.959153316146658,35.91156005859375", max_length=63
            ),
        ),
        migrations.AlterField(
            model_name="x_rays_labprofile",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="x_rays_labprofile",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="31.959153316146658,35.91156005859375", max_length=63
            ),
        ),
    ]
