# Generated by Django 4.1.1 on 2022-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_doctorprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("type", "AB+"),
                    ("type", "AB-"),
                    ("type", "A+"),
                    ("type", "A-"),
                    ("type", "B+"),
                    ("type", "B-"),
                    ("type", "O+"),
                    ("type", "O-"),
                ],
                default="AB+",
                max_length=50,
                null=True,
            ),
        ),
    ]
