# Generated by Django 4.1.1 on 2022-09-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_patientprofile_blood_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="user_info",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.patientprofile",
            ),
        ),
    ]
