# Generated by Django 4.1.1 on 2022-09-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_user_user_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.patientprofile"
            ),
        ),
    ]
