# Generated by Django 4.1.1 on 2022-09-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_remove_user_user_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.patientprofile",
            ),
        ),
    ]
