# Generated by Django 4.1.1 on 2022-09-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_patientprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_user_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
