# Generated by Django 4.1.1 on 2022-09-17 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_patientprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="user",
            field=models.ManyToManyField(
                related_name="patient_user_id", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
