# Generated by Django 4.1.1 on 2022-09-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_remove_patientprofile_user_patientprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
