# Generated by Django 4.1.1 on 2022-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_patientprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PATIENT", "Patient"),
                    ("DOCTORS", "Doctors"),
                    ("PHARMACISTS", "Pharmacists"),
                    ("LABS", "Labs"),
                    ("X_RAYS_LABS", "X_rays_labs"),
                ],
                max_length=50,
            ),
        ),
    ]
